<!DOCTYPE html>
<html>
   <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <meta name="csrf-token" content="{{ csrf_token() }}">
      <title>Instamojo Payment Gateway Integration In Laravel 8 - phpcodingstuff.com</title>
      <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
      <style>
         .mt40{
         margin-top: 40px;
         }
      </style>
   </head>
   <body>
      <div class="container">
         <div class="row">
            <div class="col-lg-12 mt40">
               <div class="card-header" style="background: #0275D8;">
                  <h2>Register for Event</h2>
               </div>
            </div>
         </div>

        

         @if ($errors->any())
         <div class="alert alert-danger">
            <strong>Opps!</strong> Something went wrong<br>
            <ul>
               @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
               @endforeach
            </ul>
         </div>
         @endif

        @isset($order_id)
        <!-- If order id exists then -->

        <h1>My order is {{$random}}</h1>

         <form action="/pay" method="POST">
            <script
                src="https://checkout.razorpay.com/v1/checkout.js"
                data-key="{{env('rzr_id')}}" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
                data-amount="{{$amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
                data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
                data-order_id="{{$order_id}}"//Replace with the order_id generated by you in the backend.
                data-buttontext="Pay with Razorpay"
                data-name="Acme Corp"
                data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
                data-image="https://example.com/your_logo.jpg"
                data-prefill.name="Gaurav Kumar"
                data-prefill.email="gaurav.kumar@example.com"
                data-prefill.mobile="7894561230"
                data-theme.color="#F37254"
            ></script>
            <input type="hidden" custom="Hidden Element" name="hidden">
        </form>

        @else

        <form action="{{ url('order') }}" method="POST">
            {{ csrf_field() }}
            <div class="row">
               <!-- <div class="col-md-12">
                  <div class="form-group">
                     <strong>Name</strong>
                     <input type="text" name="name" class="form-control" placeholder="Enter Name" required>
                  </div>
               </div>
               <div class="col-md-12">
                  <div class="form-group">
                     <strong>Mobile Number</strong>
                     <input type="text" name="mobile_number" class="form-control" placeholder="Enter Mobile Number" required>
                  </div>
               </div>
               <div class="col-md-12">
                  <div class="form-group">
                     <strong>Email Id</strong>
                     <input type="text" name="email" class="form-control" placeholder="Enter Email id" required>
                  </div>
               </div> -->
               <div class="col-md-12">
                  <div class="form-group">
                     <strong>Event Fees</strong>
                     <input type="text" name="amount" class="form-control" placeholder="" value="" required>
                  </div>
               </div>
               <div class="col-md-12">
                  <button type="submit" class="btn btn-primary">Submit</button>
               </div>
            </div>
         </form>

         @endisset
      </div>
   </body>
</html>